### ISSUE TITLE
License should be GPL instead of AGPL

### ISSUE THREAD

**Issue by leodag** [Miei/TOS-lua#11]
Since this is a client-side mod, there is no reason to use AGPL, since it doesn't transmit over the network at all. It just creates confusion for those who want to build something over/using your work. See [this](http://www.gnu.org/licenses/agpl-3.0.en.html) for reference.

**Comment by TehSeph** [comment]
I know this isn't my repo, but I have a feeling Miei added the AGPLv3 license to her repo because I added it to our other collaborative addon-related repos and also my own, so I'm curious...

GPLv3 is more updated to include clauses for DRM, Patents, and a requirement for inclusion of source code in distributed copies of the software. See [this](http://www.groklaw.net/article.php?story=20060118155841115) nifty side-by-side for all of the changes. AGPLv3 further extends GPLv3 to include any hosted services using the code to be considered as distribution and also trigger the copyleft requirements of the license.

Switching to GPLv2 just seems like a downgrade imo, but I'm also not a lawyer. What are the benefits you speak of for GPLv2 and how is it a disadvantage to be on the AGPLv3 license?

**Comment by leodag** [comment]
Oh, sorry, I misread and thought it used AGPLv1, thus suggested the direct equivalent. I have nothing against using GPLv3 for this case (not a lawyer either though), since I don't think any of the differences apply on the case of a game mod.

I don't know whether there are any disadvantages to using AGPLv3 over GPLv3 - the problem was with AGPLv1 which made it incompatible with GPLv2, but AGPLv3 is compatible with GPLv3. I still recommend to change the license to GPLv3 since the "special clause" of AGPL doesn't apply at all, as it's meant for servers. It just creates confusion.

**Comment by TehSeph** [comment]
Ah makes more sense. I will agree that the added DRM and patent clauses from v3 aren't needed for ToS addons, but the shift in language is a must have. Being restricted to US law when dealing with an international project is a bad idea. lol

Also, about AGPLv3's new clause not applying; It does apply! Again, I think you're getting confused and thinking it means code running on a network, when really it means code hosted over a network. This clause actually makes it a perfect fit for services like Git and Github, since a fork of the repo would trigger the clause and the copyleft requirements.

**Comment by leodag** [comment]
>I think you're getting confused and thinking it means code running on a network, when really it means code hosted over a network

No, it doesn't. If that was true, then every project would use AGPL, since even the linux kernel's source is hosted through the network (eg. kernel.org). AGPL's clause applies to cases where the software itself (the application) is not distributed, however is acessible through the network (eg. a database server). An example is MongoDB server: it's licensed under AGPL (unless you buy a commercial license), so if you modify the server, you must make the source code avaliable to everyone that has acess to your server. While if it used GPL, you would only be obligated to distribute the source code to the people who run the server.

>This clause actually makes it a perfect fit for services like Git and Github, since a fork of the repo would trigger the clause and the copyleft requirements.

This is true for GPL too.

**Comment by TehSeph** [comment]
I see. I've misread then. To me this indicated the software needed to be downloaded or hosted.

>To "convey" a work means any kind of propagation that enables other
parties to make or receive copies.  Mere interaction with a user through
a computer network, with no transfer of a copy, is not conveying.

But later on in the actual clause it does make mention of transfer over a network.
> Notwithstanding any other provision of this License, if you modify the
Program, your modified version must prominently offer all users
interacting with it remotely through a computer network (if your version
supports such interaction) an opportunity to receive the Corresponding
Source of your version by providing access to the Corresponding Source
from a network server at no charge, through some standard or customary
means of facilitating copying of software.

I still don't see any issue with using AGPL, however I guess it is unneeded for clientside software.
