### ISSUE TITLE
Can't right click on names in chat that have links in their message

### ISSUE THREAD

**Issue by mimiha** [Miei/TOS-lua#17]
(Classic Chat mod) I'm unable to right click and report bots that put links in their messages.

Furthermore, this also applies to any person who links an item or a party, as I'm unable to right click their name either.

So in short if there's some kind of link (external, item, party) I can't right click their name in chat.

**Comment by Miei** [comment]
This is a problem with the game itself. Try clicking all the way to the right of the message instead.

The game disables "hit test" for a message if it has any type of link in it, which means you can't right click the message, at least where the text is. It does this to enable you to click the link itself, otherwise you would not be able to do so.

I admit that the effect may be exaggerated with classic chat installed since I am expanding the messages to fill the chat box, but even so.
