### ISSUE TITLE
ClassicChat Bug

### ISSUE THREAD

**Issue by xapola** [Miei/TOS-lua#6]
ClassicChat Addon seems to break when login in whit an low durability equip, the text in the chat bubble (and the bubble) will stay at the bottom of the chat box until completely restarting the game without any equipment whit low durability.

![chat1](https://cloud.githubusercontent.com/assets/19356884/15266356/859ff5e8-1978-11e6-8a3b-d88a6acb447d.jpg)

![chat2](https://cloud.githubusercontent.com/assets/19356884/15266359/9663df16-1978-11e6-91cc-4428e1ead6a5.jpg)

Edit:Can't seem to replicate bug consistently.

**Comment by Miei** [comment]
So, the 30% duration message should be purely a visual bug. That should not be sticking at the bottom of your chat. It just happens that the message got through before classicChat loaded up to style it.

The screenshot with shout chat I can understand. The message got through before the game had successfully requested the server time, so it used your local timezone which is ahead of the server time. Since the messages are ordered by the time they are sent, it sticks to the bottom of your chat window. I think that's how the bug works. You can see that the newer messages are actually an hour behind on the timestamp.

This is an issue with the game regardless of whether classicChat is installed or not and if you continue to have it, I would recommend that you install Context Menu Additions on [Excrulon's repo](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods). This will allow you to remove a message from the chat's context menu (right click). So you can remove any messages that get stuck.
